### ISSUE TITLE
Reddot APIs

### ISSUE THREAD

**Issue by ronaldaug** [reddotpay/jspay#16]
Excuse me, I'm new to Reddot. 

What is the different between these two API? 

**1 - https://reddotpayment.com/developers** 
and
**2 - https://github.com/reddotpay/jspay**

Could someone explain me? Thanks in advance.

I can clearly see the request servers and the parameters are not the same.
The first API's URL is https://secure-dev.reddotpayment.com/service/payment-api
and the second API's URL is https://connect2.api.reddotpay.sg/v1/

**Comment by gianebao** [comment]
https://reddotpayment.com/developers refers to the old system, also called **API2**. 

https://github.com/reddotpay/jspay is the Javascript SDK to create a hosted payment page, using the iframe, with the new API3 system. the documentation should be available in https://connect2.reddotpay.sg (for staging)
